language: ruby
rvm:
  - 2.5.1
cache:
  - bundler
services:
  - postgresql
before_script:
  - cp config/database.yml.travis config/database.yml
  - cp config/application.yml.travis config/application.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - bundle install
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec