GET http://{{host}}:{{port}}/api/users/100/follows
Accept: application/json
Content-Type: application/json

###

GET http://{{host}}:{{port}}/api/users/100/follows/count
Accept: application/json
Content-Type: application/json

###

POST http://{{host}}:{{port}}/api/users/94/follows/
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

{
  "follow_id": 1
}

###

DELETE http://{{host}}:{{port}}/api/users/94/follows/1
Accept: application/json
Content-Type: application/json
Authorization: {{token}}
